name: build-docs
description: 'Build the documentation for the public site'
on:
  push:
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        fetch-depth: 0
        ref: gh-pages
      - name: Build docs
        run: ./bin/build-docs.sh
        env:
          GIT_AUTHOR_NAME: "Documentation updater [bot]"
          GIT_AUTHOR_EMAIL: "bot-github.com@pileofstuff.org"
